parameters:
    # Adds fallback params in case the corresponding env vars are not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(GOS_WEB_SOCKET_SERVER_IP): '127.0.0.1'
    env(GOS_WEB_SOCKET_SERVER_PORT): 1337

gos_web_socket:
    server:
        port: '%env(int:GOS_WEB_SOCKET_SERVER_PORT)%' # The port the socket server will listen on
        host: '%env(GOS_WEB_SOCKET_SERVER_IP)%'       # The host ip to bind to
        router:
            resources:
                -
                    resource: '%kernel.project_dir%/config/pubsub/websocket/*'
                    type: 'glob'
    client:
        firewall: main
        session_handler: 'session.handler.pdo'
    pushers:
        wamp:
            enabled: true # Flag to enable this pusher
            host: '%env(GOS_WEB_SOCKET_SERVER_IP)%' # This will probably be the same as your `gos_web_socket.server.host` value
            port: '%env(int:GOS_WEB_SOCKET_SERVER_PORT)%' # This will probably be the same as your `gos_web_socket.server.port` value
            ssl: false # Flag to enable SSL connections to the websocket server, default false
            origin: null # The origin domain for the pusher, default null (if origin checking is enabled on your websocket server, this value must be allowed)