message_topic:
    channel: message/channel/{idChannel}
    handler: 'message.topic'
    
notif_topic:
    channel: notif/{idUser}
    handler: 'notif.topic'

userevent_topic:
    channel: user/{idUser}
    handler: 'userevent.topic'

privateevent_topic:
    channel: privateUserEvent/{idUser}
    handler: 'privateevent.topic'

channelevent_topic:
    channel: channelEvent/{idChennel}
    handler: 'channelevent.topic'